name: Verify CI

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  verify_valid:
    name: Verify valid image
    uses: PrintScript8/ingsis-library/.github/workflows/on-pull-request.yml@main
    secrets: inherit
    environment:
      AUTH0_SECRET_KEY: ${{ secrets.AUTH0_SECRET_KEY }}

  publish_docker:
    name: Publish Docker image
    needs: verify_valid
    uses: PrintScript8/ingsis-library/.github/workflows/docker-image.yml@main
    with:
      service_name: ${{ github.ref == 'refs/heads/main' && 'authorization' || 'authorization-dev' }}

  rerun_image:
    name: Rerun Docker image
    needs: publish_docker
    uses: PrintScript8/ingsis-library/.github/workflows/vm-login.yml@main
    with:
      service_name: ${{ github.ref == 'refs/heads/main' && 'authorization' || 'authorization-dev' }}
      port: "8086"
      is_dev: ${{ github.ref == 'refs/heads/dev' }}
      is_image: true
    secrets: inherit

permissions:
  packages: write